{{- if .Values.configMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "activemq.fullname" . }}-config
  labels: {{ include "activemq.labels" . | nindent 4 }}
data:
{{- range $name, $config := .Values.configMap }}
  {{ $name }}: |
{{ $config | indent 4 -}}
{{- end -}}
{{- end -}}