name: 'release'
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
  

jobs:
  # The "build" workflow
  lint-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      
      - name: Lint chart
        run:  helm lint deploy/helm/activemq

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0

      - name: Install chart
        run: |
          helm install activemq deploy/helm/activemq -n activemq --create-namespace --wait
  
  release_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses:  docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            webcenter/activemq-kube
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  publish-pr:
    needs: [lint-test, release_docker_image]
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request')
    steps:
      - uses: actions/checkout@v2
      - name: Update chart version
        run: |
          #!/bin/sh
          cd deploy/helm
          sed -i -E 's/version:(.*)/version: \1-pr${{ github.event.pull_request.number }}/g' activemq/Chart.yaml
          sed -i -E 's/imageTag:(.*)/imageTag: pr-${{ github.event.pull_request.number }}/g' activemq/values.yaml
        
      - uses: goodsmileduck/helm-push-action@v3.3.1
        env:
          SOURCE_DIR: 'deploy/helm'
          CHART_FOLDER: 'activemq'
          FORCE: 'True'
          CHARTMUSEUM_URL: 'https://charts.webcenter.fr'
          CHARTMUSEUM_USER: '${{ secrets.CHARTMUSEUM_USER }}'
          CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}

  publish:
    needs: [lint-test, release_docker_image]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - uses: goodsmileduck/helm-push-action@v3.3.1
        env:
          SOURCE_DIR: 'deploy/helm'
          CHART_FOLDER: 'activemq'
          FORCE: 'True'
          CHARTMUSEUM_URL: 'https://charts.webcenter.fr'
          CHARTMUSEUM_USER: '${{ secrets.CHARTMUSEUM_USER }}'
          CHARTMUSEUM_PASSWORD: ${{ secrets.CHARTMUSEUM_PASSWORD }}
      




   